version: '3.8'

services:
  web:
    build: .
    container_name: web
    command: gunicorn D.Z.30.1.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - db
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    expose:
      - "6379"
    volumes:
      - redis_data:/data

  db:
    image: postgres:latest
    container_name: db
    expose:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: your_database_name
      POSTGRES_USER: your_database_user
      POSTGRES_PASSWORD: your_database_password
    env_file:
      - .env

  celery:
    build: .
    container_name: celery
    command: celery -A D.Z.30.1 worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

  celery-beat:
    build: .
    container_name: celery-beat
    command: celery -A D.Z.30.1 beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis
    env_file:
      - .env

volumes:
  redis_data:
  postgres_data:
